//! Comments - the sarcastic annotations that make disassembly bearable

use rand::seq::SliceRandom;

// Comments for specific instruction patterns
pub fn get_instruction_comment(mnemonic: &str, operands: &str) -> Option<&'static str> {
    match mnemonic {
        "push" if operands.contains("rbp") => Some("; the ritual begins"),
        "push" if operands.contains("rax") => Some("; saving for a rainy day"),
        "push" => Some("; push it real good"),
        
        "pop" if operands.contains("rbp") => Some("; the ritual ends"),
        "pop" => Some("; pop goes the weasel"),
        
        "mov" if operands.contains("rsp") && operands.contains("rbp") => Some("; establishing dominance"),
        "mov" if operands.contains("0xdeadbeef") => Some("; classic"),
        "mov" if operands.contains("0xcafebabe") => Some("; java was here"),
        "mov" if operands.contains("0xbaadf00d") => Some("; bad food indeed"),
        "mov" if operands.contains("0x0") => Some("; null and void"),
        "mov" if operands.contains("eax, 0") => Some("; could've used xor, just saying"),
        "mov" => Some("; mov money mov problems"),
        
        "xor" if operands.contains("eax, eax") => Some("; the elegant zero"),
        "xor" if operands.contains("self") => Some("; trust no one, not even yourself"),
        "xor" => Some("; exclusive or inclusive, make up your mind"),
        
        "call" if operands.contains("malloc") => Some("; memory leak incoming"),
        "call" if operands.contains("free") => Some("; or is it?"),
        "call" if operands.contains("printf") => Some("; debug by print, the ancient way"),
        "call" if operands.contains("exit") => Some("; goodbye cruel world"),
        "call" if operands.contains("fork") => Some("; now there are two of them"),
        "call" if operands.contains("sleep") => Some("; zzz"),
        "call" if operands.contains("system") => Some("; shell we dance?"),
        "call" => Some("; calling for help"),
        
        "ret" => Some("; return to sender"),
        
        "jmp" if operands.contains("0x666") => Some("; to hell we go"),
        "jmp" => Some("; yeet"),
        
        "je" | "jz" => Some("; equal opportunity jumper"),
        "jne" | "jnz" => Some("; not taking no for an answer"),
        "jg" | "ja" => Some("; feeling greater today"),
        "jl" | "jb" => Some("; taking the low road"),
        
        "cmp" => Some("; judging silently"),
        "test" => Some("; pop quiz"),
        
        "nop" => Some("; this is fine"),
        
        "lea" => Some("; load effective anxiety"),
        
        "add" if operands.contains("rsp") => Some("; cleaning up after ourselves"),
        "add" => Some("; math is hard"),
        
        "sub" if operands.contains("rsp") => Some("; making room for our problems"),
        "sub" => Some("; subtraction: the lesser addition"),
        
        "mul" | "imul" => Some("; multiply your problems"),
        "div" | "idiv" => Some("; divide and conquer (or crash)"),
        
        "int" if operands.contains("3") => Some("; break time!"),
        "int" if operands.contains("0x80") => Some("; old school syscall"),
        "syscall" => Some("; please kernel-senpai"),
        
        "leave" => Some("; bye felicia"),
        
        "rep" => Some("; repeat after me"),
        
        "and" => Some("; this AND that"),
        "or" => Some("; this OR that OR existential crisis"),
        "not" => Some("; rebellion!"),
        
        "shl" | "sal" => Some("; shift happens"),
        "shr" | "sar" => Some("; right shift into madness"),
        
        "inc" => Some("; one more problem"),
        "dec" => Some("; one less problem"),
        
        "hlt" => Some("; halt! who goes there?"),
        
        _ => None,
    }
}

// Random generic comments when we don't recognize the instruction
const GENERIC_COMMENTS: &[&str] = &[
    "; seems legit",
    "; what could go wrong",
    "; here be dragons",
    "; TODO: understand this",
    "; this is where the magic happens",
    "; don't ask me, I just work here",
    "; probably important",
    "; ¯\\_(ツ)_/¯",
    "; trust the process",
    "; it works, don't touch it",
    "; cursed",
    "; blessed",
    "; blursed",
    "; written by an intern",
    "; generated by AI (copilot was here)",
    "; this took 4 cups of coffee",
    "; I have no idea what this does",
    "; technical debt++",
    "; [citation needed]",
    "; (elevator music)",
];

pub fn get_random_comment() -> &'static str {
    let mut rng = rand::thread_rng();
    GENERIC_COMMENTS.choose(&mut rng).unwrap_or(&"; huh")
}

// Comments for function names
pub fn get_function_comment(name: &str) -> &'static str {
    if name.contains("main") {
        "    ; where it all begins (and usually ends in tears)"
    } else if name.contains("init") {
        "    ; initialization: the hopeful phase"
    } else if name.contains("exit") || name.contains("fini") {
        "    ; cleanup crew"
    } else if name.contains("malloc") || name.contains("alloc") {
        "    ; memory allocation (leak factory)"
    } else if name.contains("free") {
        "    ; memory deallocation (use after free, probably)"
    } else if name.contains("csu") {
        "    ; C runtime sorcery"
    } else if name.contains("libc") {
        "    ; blessed by the C gods"
    } else if name.contains("pthread") {
        "    ; threading: here be race conditions"
    } else if name.contains("crypto") || name.contains("aes") || name.contains("sha") {
        "    ; cryptographic mystery"
    } else if name.contains("error") || name.contains("fail") {
        "    ; bad vibes only"
    } else if name.contains("debug") {
        "    ; printf was here"
    } else if name.contains("test") {
        "    ; hopefully tested"
    } else if name.contains("flag") {
        "    ; CTF{obvious_flag_location}"
    } else {
        "    ; function does things"
    }
}
